# @package _global_

# uses only 1% of the training data and 5% of validation/test data

defaults:
  - default.yaml
  - override /logger: wandb.yaml

wandb: 
  project: debug
  entity: prosody 

trainer:
  max_epochs: 5
  limit_train_batches: 0.1
  limit_val_batches: 0.05
  limit_test_batches: 0.05
